[phases.setup]
nixPkgs = ['nodejs_20', 'chromium', 'glibc', 'glib', 'gobject-introspection', 'pango', 'cairo', 'nss', 'nspr', 'atk', 'at-spi2-atk', 'cups', 'dbus', 'gtk3', 'libdrm', 'libxkbcommon', 'libgbm', 'alsa-lib', 'xorg.libX11', 'xorg.libXcomposite', 'xorg.libXdamage', 'xorg.libXext', 'xorg.libXfixes', 'xorg.libXrandr', 'xorg.libxshmfence', 'gcc-unwrapped']

[phases.build]
cmds = ['npm install']

[start]
cmd = 'node index.js'
